### ISSUE TITLE
The extension needs to be dropped and recreated if Postgres is restarted

### ISSUE THREAD

**Issue by ramarnat** [duckdb/pg_duckdb#160]
What's the best way to debug what's going on here? There doesnt seem to be anything in the log to indicate that it was unable to load the extension.

Some details:
I am running postgres in a container, it's version 16. I built the extension from code and then ran the make install. I can share the dockefile if needed.

**Comment by wuputah** [comment]
Thanks for opening this, it's an otherwise undocumented issue that we should fix. Postgres won't load a library unless it needs it (like you use a function that is defined in C, or use a tableam, etc). Right now, the functions are defined in SQL, so the library does not get loaded when you try to use one of the functions.

Right now the easiest workaround is adding it to `shared_preload_libraries`. Using `LOAD pg_duckdb;` should also work.
