### ISSUE TITLE
"EXPLAIN" statement Segmentation fault

### ISSUE THREAD

**Issue by Leo-XM-Zeng** [duckdb/pg_duckdb#279]
**Current Behavior**
```plpgsql
postgres=# set duckdb.execution = true;
SET
postgres=# create table ta(a int);
CREATE TABLE
postgres=# explain SELECT count(*) FROM ta;
2024-10-14 16:40:30.331 CST [1621] WARNING:  01000: relcache reference leak: relation "ta" not closed
2024-10-14 16:40:30.331 CST [1621] LOCATION:  PrintRelCacheLeakWarning, resowner.c:1203
WARNING:  relcache reference leak: relation "ta" not closed
                         QUERY PLAN                         
------------------------------------------------------------
 Custom Scan (DuckDBScan)  (cost=0.00..0.00 rows=0 width=0)
   DuckDB Execution Plan: 
 
 ┌───────────────────────────┐
 │    UNGROUPED_AGGREGATE    │
 │    ────────────────────   │
 │        Aggregates:        │
 │        count_star()       │
 └─────────────┬─────────────┘
 ┌─────────────┴─────────────┐
 │     POSTGRES_SEQ_SCAN     │
 │    ────────────────────   │
 │         Function:         │
 │     POSTGRES_SEQ_SCAN     │
 │                           │
 │         ~2550 Rows        │
 └───────────────────────────┘
 
 
(19 rows)

postgres=# \q
[postgres@halo-centos8 ~]$ 2024-10-14 16:40:33.891 CST [1607] LOG:  00000: server process (PID 1621) was terminated by signal 11: Segmentation fault
```

**Comment by Leo-XM-Zeng** [comment]
"explain" statement has a resource management problem, but I can't find out how to fix it

**Comment by JelteF** [comment]
Hmm, that's not good. I can reproduce this, although for me it is throwing an assert failure because I compile postgres with asserts enabled. 

The segfault/assert failure is fixed/worked around for me in #267. I presume because we don't call the destructor of DuckDB anymore at process exit, which seems to be the reason why it's crashing. It seems we're calling `RelationClose` too late in this case for some reason.

**Comment by JelteF** [comment]
We should definitely fix the resource leak too though.

**Comment by Leo-XM-Zeng** [comment]
Maybe there's a "relation_close" function call missing somewhere

**Comment by mkaruza** [comment]
It leaks because destructor of `PostgresTable` is not called. It is interesting because same execution is applied for Scan & Explain callback - only difference is that we, in Scan callback, call `query_result->Fetch()` until we receive nullptr (is exhausted) which will in return call destructor. For explain we don't do that and call `Fetch()` only once - adding extra Fetch() will do cleanup.

**Comment by Y--** [comment]
> It leaks because destructor of `PostgresTable` is not called. It is interesting because same execution is applied for Scan & Explain callback - only difference is that we, in Scan callback, call `query_result->Fetch()` until we receive nullptr (is exhausted) which will in return call destructor. For explain we don't do that and call `Fetch()` only once - adding extra Fetch() will do cleanup.

Yeah that would work too, but I instead [opted](https://github.com/duckdb/pg_duckdb/pull/281/files/2950912067dc95543f457dbf6becf375f6950c51#diff-343901dd6406bdcd8358c4ec972584c30c7dfc01f7f1030360f6815c8626b68e) for removing it in the "Rollback" phase of the `PostgresTransactionManager`, which might have leaked other table anyway. WDYT?

**Comment by JelteF** [comment]
I think doing both fixes makes sense, i.e. handling rollback correctly, and calling Fetch until the end for EXPLAIN queries.

It sounds like not calling fetch until the end will eventually cause a Rollback, which would be problematic once we implement write support. Because then an `EXPLAIN ANALYZE INSERT ...` would probably not actually run the insert.

But obviously we should be handling rollbacks correctly too. They can happen on any failure.

**Comment by Y--** [comment]
++ Added this to my PR as well.
