### ISSUE TITLE
`make clean` doesn't clean duckdb's build folder

### ISSUE THREAD

**Issue by bleskes** [duckdb/pg_duckdb#317]
### What happens?

I had an old checkout and it failed to build. Running `make clean` didn't help until I run `rm -rf third_pary/duckdb/build` .

### To Reproduce

see above

### OS:

mac os

### pg_duckdb Version:

main

### Postgres Version:

17

### Full Name:

Boaz Leskes

### Affiliation:

MD

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by JelteF** [comment]
I think there's two parts of this:
1. Running `make` was not enough to get the correct duckdb build
2. The `make clean-all` command is not discoverable enough. That one also cleans the duckdb build.

The main reason why `make clean` does not clean the duckdb build is because normally you don't need to rebuild it and building duckdb is slow even with ccache. And if you're switching between Postgres versions you'll need to run `make clean` to clean up the actual extension artifacts.

**Comment by JelteF** [comment]
Closing this, because problem 1 is fixed now by #406
